# Generated by Django 4.2.2 on 2024-07-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    (
                        "can_change_product_description",
                        "Can change product description",
                    ),
                    ("can_change_product_category", "Can change product category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
